### ISSUE TITLE
Erro de precedência no teste da US5

### ISSUE THREAD

**Issue by jonathantvrs** [matheusgr/p2#4]
Para que a precedência da especificação funcione é necessário alterar as linhas 42, 43 do teste de aceitação da us5. Com essa alteração, o algoritmo de validação abaixo funciona:

1º Tema vazio/nulo
2º Politicos vazio/nulo
3º Dni Inválido
4º Tema Existente
5º Pessoa Inexistente
6º Pessoa não é deputado

**Comment by matheusgr** [comment]
os testes das linhas 42 e 43 não são para testar precedência, apenas para testar o cadastro de uma pessoa que não é deputado.

**Comment by jonathantvrs** [comment]
Exatamente, @matheusgr . Se for para seguir essa precedência de testes no código, vai dar conflito ou nessas linhas ou nas linhas que testam precedência. Nós já implementamos e mesmo rearranjando os testes de outras maneiras, nenhuma passa a não ser que altere o arquivo de testes. Se quiser, te convido para olhar o nosso código e até executá-lo na sua máquina. O senhor tem acesso ao nosso projeto https://github.com/jonathantvrs/e-co.git

**Comment by matheusgr** [comment]
entendi o problema agora. reabrindo para resolver o problema.

**Comment by matheusgr** [comment]
resolvido em: adc728b1d26c84df7256da3adf006b8edfaf18da
