### ISSUE TITLE
Erro nos testes da US6. Não esta lançando exception

### ISSUE THREAD

**Issue by AntonioNtV** [matheusgr/p2#8]
`cadastrarPL dni="061222222-0" ano=1987 ementa="Institui a semana da nutricao nas escolas" interesses="saude,educacao basica" url="http://example.com/semana_saude" conclusivo=true
cadastrarPL dni="061222222-0" ano=3000 ementa="Institui a semana do carinho nas escolas" interesses="cidadania,educacao basica" url="http://example.com/semana_cidadania" conclusivo=false
cadastrarPLP dni="061444444-0" ano=2020 ementa="Regulamenta a tributacao de apostas eletronicas" interesses="fiscal,jogos" url="https://example.net/jogos%40aposta" artigos="153"
cadastrarPEC dni="061222222-0" ano=-1 ementa="Permite a associacao sindical livre e com estrutura hierarquica" interesses="trabalho" url="https://example.com/sindicato/algo.html" artigos="7,8"`

Era esperar um lançamento de exception.

**Comment by AntonioNtV** [comment]
`cadastrarPL dni="061222222-0" ano=1987 ementa="Institui a semana da nutricao nas escolas" interesses="saude,educacao basica" url="http://example.com/semana_saude" conclusivo=true
cadastrarPL dni="061222222-0" ano=3000 ementa="Institui a semana do carinho nas escolas" interesses="cidadania,educacao basica" url="http://example.com/semana_cidadania" conclusivo=false
cadastrarPLP dni="061444444-0" ano=2020 ementa="Regulamenta a tributacao de apostas eletronicas" interesses="fiscal,jogos" url="https://example.net/jogos%40aposta" artigos="153"
cadastrarPEC dni="061222222-0" ano=-1 ementa="Permite a associacao sindical livre e com estrutura hierarquica" interesses="trabalho" url="https://example.com/sindicato/algo.html" artigos="7,8"`


Era esperar um lançamento de exception.

**Comment by matheusgr** [comment]
resolvido.
